name: Ziti Webhook Workflow
on:
  workflow_call:
  workflow_dispatch:

jobs:
  ziti-webhook:
    runs-on: ubuntu-latest
    name: Ziti Webhook Job
    steps:
      - name: Send Webhook
        uses: openziti/ziti-webhook-action@v2
        if: ${{ env.ZITI_WEBHOOK_SECRET != null }}
        env:
          ZITI_WEBHOOK_SECRET: ${{ secrets.ZITI_WEBHOOK_SECRET }}
        with:
          ziti-id: ${{ secrets.ZITI_WEBHOOK_ACTION_ID }}
          webhook-url: http://webhookz.ziti/post
          webhook-secret: ${{ secrets.ZITI_WEBHOOK_SECRET }}
