name: Ziti Webhook Workflow
on:
  workflow_call:

jobs:
  ziti-webhook:
    runs-on: ubuntu-latest
    name: Ziti Webhook Job
    steps:
      - name: Send Webhook
        uses: openziti/ziti-webhook-action-py@v1
        if: ${{ env.ZITI_WEBHOOK_IDENTITY != null }}
        env:
          ZITI_WEBHOOK_IDENTITY: ${{ secrets.ZITI_WEBHOOK_IDENTITY }}
        with:
          zitiId: ${{ secrets.ZITI_WEBHOOK_IDENTITY }}
          webhookUrl: http://webhookz.ziti/post
          eventJson: ${{ toJson(github.event) }}
